### ISSUE TITLE
Request for Arch Version

### ISSUE THREAD

**Issue by benzai10** [relf108/OSX-KVM-installer#1] opened 2020-09-03 06:20 UTC
Sounds like an awesome package. Would love to see it available for Arch/pacman. Thanks!

**Comment by relf108** [comment] 2020-09-03 23:11
I've had a few requests for this so I just wanted to let you know I'm getting started on it. Thanks for the feedback :)

**Comment by relf108** [comment] 2020-09-04 07:30
There is a beta release now available on pub.dev. It is minimally tested so any feedback is much appreciated. To install from pub.dev just run.
`pub global activate osx_kvm_installer`
`osx_kvm_installer`

**Comment by benzai10** [comment] 2020-09-19 10:35
Thanks for the beta release. I finally found some time to test it. The ```osx_kvm_installer``` launches but ends up with following error:

```
sudo: apt-get: command not found
Unhandled exception:
sudo apt-get install python qemu uml-utilities virt-manager dmg2img git wget libguestfs-tools -y
exit: 1
reason: The command [sudo] with args [apt-get, install, python, qemu, uml-utilities, virt-manager, dmg2img, git, wget, libguestfs-tools, -y] failed with exitCode: 1
#0      waitForEx (package:dcli/src/util/wait_for_ex.dart:39:7)
#1      RunnableProcess.processUntilExit (package:dcli/src/util/runnable_process.dart:390:7)
#2      RunnableProcess.run (package:dcli/src/util/runnable_process.dart:153:11)
#3      start (package:dcli/src/functions/run.dart:208:19)
#4      StringAsProcess.start (package:dcli/src/util/string_as_process.dart:159:5)
#5      AptPackageManger.installDependencies (package:osx_kvm_installer/src/package_managers/apt_package_manager.dart:9:12)
#6      install (package:osx_kvm_installer/src/install.dart:8:6)
#7      main (file:///home/bzt/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/osx_kvm_installer-0.0.7/bin/osx_kvm_installer.dart:7:3)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by relf108** [comment] 2020-09-19 10:38
Thanks so much for your time. Looks like the code for detecting Pacman isn't behaving itself. I'll try and get another release to you before the end of next week.

**Comment by relf108** [comment] 2020-09-24 03:35
I've just pushed another release (0.0.8) to pub dev. Again, untested so If you've got some time to have another go at it that would be fantastic.

**Comment by benzai10** [comment] 2020-09-24 10:16
I don't know if I'm not patient enough but I think the installation process got stuck (nothing happened after 30 mins..):

```
Pacman detected, if you do not have AUR packages enabled the installer will now do so. Press any button to continue or [n(N)] to stop
:: Synchronizing package databases...
downloading core.db...
downloading extra.db...
downloading community.db...
warning: autoconf-2.69-7 is up to date -- skipping
warning: automake-1.16.2-3 is up to date -- skipping
warning: binutils-2.35-2 is up to date -- skipping
warning: bison-3.6.4-1 is up to date -- skipping
warning: fakeroot-1.24-2 is up to date -- skipping
warning: file-5.39-1 is up to date -- skipping
warning: findutils-4.7.0-2 is up to date -- skipping
warning: flex-2.6.4-3 is up to date -- skipping
warning: gawk-5.1.0-1 is up to date -- skipping
warning: gcc-10.2.0-2 is up to date -- skipping
warning: gettext-0.21-1 is up to date -- skipping
warning: grep-3.4-1 is up to date -- skipping
warning: groff-1.22.4-3 is up to date -- skipping
warning: gzip-1.10-3 is up to date -- skipping
warning: libtool-2.4.6+42+gb88cebd5-14 is up to date -- skipping
warning: m4-1.4.18-3 is up to date -- skipping
warning: make-4.3-3 is up to date -- skipping
warning: pacman-5.2.2-1 is up to date -- skipping
warning: patch-2.7.6-8 is up to date -- skipping
warning: pkgconf-1.7.3-1 is up to date -- skipping
warning: sed-4.8-1 is up to date -- skipping
warning: texinfo-6.7-3 is up to date -- skipping
warning: which-2.21-5 is up to date -- skipping
 multilib is up to date
:: There is 1 member in group base-devel:
:: Repository core


```

**Comment by relf108** [comment] 2020-09-25 00:22
If an error was thrown the code should have passed it up and displayed it. It looks like the installer was enabling AUR which can take a long time, but it's hiding the output of the command doing so. I'll change the system to show said output so that you can see progress. Overall, I have a feeling that we're on the right track here.

EDIT: In hindsight it I'm actually thinking that Pacman is prompting the user for input and it's to getting displayed. I'll see what I can do about this.

**Comment by relf108** [comment] 2020-09-25 00:40
I've just pushed another release to pub dev which simply adds the noconfirm flag to the pacman commands. This should mean that only the prompts I output should halt the install process.

**Comment by benzai10** [comment] 2020-09-25 07:19
Thanks for the new release, tried it and here's some error output, hope it helps:

```
installing libguestfs...
Optional dependencies for libguestfs
    ocaml: OCaml Bindings
    python: Python Bindings [installed]
    gobject-introspection: GObject-Introspection Bindings
:: Running post-transaction hooks...
( 1/11) Creating system user accounts...
Creating group libvirt with gid 970.
( 2/11) Reloading system manager configuration...
( 3/11) Applying kernel sysctl settings...
Not setting net/ipv4/conf/all/rp_filter (explicit setting exists).
Not setting net/ipv4/conf/default/rp_filter (explicit setting exists).
Not setting net/ipv4/conf/all/accept_source_route (explicit setting exists).
Not setting net/ipv4/conf/default/accept_source_route (explicit setting exists).
Not setting net/ipv4/conf/all/promote_secondaries (explicit setting exists).
Not setting net/ipv4/conf/default/promote_secondaries (explicit setting exists).
( 4/11) Creating temporary files...
( 5/11) Reloading device manager configuration...
( 6/11) Arming ConditionNeedsUpdate...
( 7/11) Warn about old perl modules
( 8/11) Compiling GSettings XML schema files...
( 9/11) Updating icon theme caches...
(10/11) Updating the info directory file...
(11/11) Updating the desktop file MIME type cache...
Unhandled exception:
pamac build uml-utilities
exit: 2
reason: Could not find pamac on the path.
#0      waitForEx (package:dcli/src/util/wait_for_ex.dart:39:7)
#1      RunnableProcess._waitForStart (package:dcli/src/util/runnable_process.dart:254:5)
#2      RunnableProcess.start (package:dcli/src/util/runnable_process.dart:230:7)
#3      RunnableProcess.run (package:dcli/src/util/runnable_process.dart:146:7)
#4      start (package:dcli/src/functions/run.dart:208:19)
#5      StringAsProcess.start (package:dcli/src/util/string_as_process.dart:159:5)
#6      PacmanPackageManager.installDependencies (package:osx_kvm_installer/src/package_managers/pacman_package_manager.dart:18:37)
#7      install (package:osx_kvm_installer/src/install.dart:25:6)
#8      main (file:///home/bzt/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/osx_kvm_installer-0.0.14/bin/osx_kvm_installer.dart:7:3)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by relf108** [comment] 2020-09-25 09:00
Thats odd, I was under the impression pamac was preloaded into Arch. Would you mind checking if you have pamac installed? If you don't this should just be a matter of installing pamac in the script. 
Assuming that's the case, if you install pamac manually this should fix the issue on your local machine.

**Comment by benzai10** [comment] 2020-09-25 10:42
I installed pamac and reran the script. This time, the problematic package is uml-utilities. I manually installed uml_utilities from the AUR (mind the _ in the AUR package name). Terminal output:

```
Error: target not found: uml-utilities
Unhandled exception:
pamac build uml-utilities
exit: 1
reason: The command [pamac] with args [build, uml-utilities] failed with exitCode: 1
#0      waitForEx (package:dcli/src/util/wait_for_ex.dart:39:7)
#1      RunnableProcess.processUntilExit (package:dcli/src/util/runnable_process.dart:390:7)
#2      RunnableProcess.run (package:dcli/src/util/runnable_process.dart:153:11)
#3      start (package:dcli/src/functions/run.dart:208:19)
#4      StringAsProcess.start (package:dcli/src/util/string_as_process.dart:159:5)
#5      PacmanPackageManager.installDependencies (package:osx_kvm_installer/src/package_managers/pacman_package_manager.dart:18:37)
#6      install (package:osx_kvm_installer/src/install.dart:25:6)
#7      main (file:///home/bzt/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/osx_kvm_installer-0.0.14/bin/osx_kvm_installer.dart:7:3)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by relf108** [comment] 2020-09-25 12:10
Ah, I probably hard coded the build command and if it's already installed this will fail. I've got some code which lets you skip the dependency installation and ill add a flag tomorrow to enable enable it so that we can get this operational for you as I hate to consume too much of your time. I'll also fix up that pamac build issue. (hopefully it's just that missing '_')
Once again, thank you for your contribution, it's been an enormous help.

**Comment by relf108** [comment] 2020-09-26 06:08
I have just published a release which attempts to fix the issues you were facing building uml utils. If that is not working and you have all the dependencies installed, (I think you should by now) you can pass the flag -s to skip dependency install. I've thoroughly tested the installer with the -s flag passed in so I'm pretty sure this will work.

**Comment by benzai10** [comment] 2020-09-29 08:00
I used the flag -s and I got so far that the BaseSystem got decompressed but after choosing the size of install (default 64GB), it says ```Cannot find device "virbr0"``` and then it's stuck with repeating error messages saying

```tap0 unavailable freeing resource and retrying 0Cannot find device "virbr0"```

Any ideas?

**Comment by relf108** [comment] 2020-09-29 11:07
The original project this is based on says this might be caused by virbr0 being disabled on your system (I have a feeling this is a common issue on arch based distributions). Running either of these commands should enable it if this is the case and fix your issue.

```
virsh net-start default
virsh net-autostart default
```
Also, I'll fix that error you encountered, its only meant to makes 3 attempts.
On a side note this means that the vm has been created and this is just networking set up.

**Comment by benzai10** [comment] 2020-09-30 13:39
After setting up the libvirt environment with its correct network configuration, everything worked! Thanks. Unfortunately, on my rather old laptop with no dGPU or eGPU, Xcode and Safari suffer from graphical artifacts that make it unusable. But macOS (Catalina) as such works. Never mind, thanks for your help and I will retry when I have a better machine.

**Comment by relf108** [comment] 2020-09-30 23:22
Super glad we got you up and running, thanks for all you're patience and testing over the past couple weeks, it's been incredibly helpful. 
Closing this issue :)

**Closed as completed** 2020-09-30 23:22 UTC

**Comment by jaekim24** [comment] 2022-12-31 01:21
> I installed pamac and reran the script. This time, the problematic package is uml-utilities. I manually installed uml_utilities from the AUR (mind the _ in the AUR package name). Terminal output:
> 
> ```
> Error: target not found: uml-utilities
> Unhandled exception:
> pamac build uml-utilities
> exit: 1
> reason: The command [pamac] with args [build, uml-utilities] failed with exitCode: 1
> #0      waitForEx (package:dcli/src/util/wait_for_ex.dart:39:7)
> #1      RunnableProcess.processUntilExit (package:dcli/src/util/runnable_process.dart:390:7)
> #2      RunnableProcess.run (package:dcli/src/util/runnable_process.dart:153:11)
> #3      start (package:dcli/src/functions/run.dart:208:19)
> #4      StringAsProcess.start (package:dcli/src/util/string_as_process.dart:159:5)
> #5      PacmanPackageManager.installDependencies (package:osx_kvm_installer/src/package_managers/pacman_package_manager.dart:18:37)
> #6      install (package:osx_kvm_installer/src/install.dart:25:6)
> #7      main (file:///home/bzt/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/osx_kvm_installer-0.0.14/bin/osx_kvm_installer.dart:7:3)
> #8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
> #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
> ```

how were you able to install pacmac im having a hard time doing it
